name: 'snowflake_tpch_demo'
version: '1.0'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  snowflake_tpch_demo:
    staging:
      +materialized: view #silver
    marts:
      +materialized: table #gold
