version: 2

models:
  - name: stg_orders
    description: "Silver: orders joined with customer; adds customer_name and order_year."
    columns:
      - name: order_key
        tests: [not_null, unique]
      - name: customer_key
      - name: customer_name
      - name: order_year

  - name: customer_revenue
    description: "Gold: total revenue per customer from LINEITEM * (1 - discount)."
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_name
      - name: total_revenue

sources:
  - name: tpch
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    description: "TPC-H sample data in Snowflake."
    tables:
      - name: customer
      - name: orders
      - name: lineitem
