version: 2

models:
  # silver
  - name: stg_orders
    description: "Silver: orders joined with customer; adds customer_name and order_year."
    columns:
      - name: order_key
        tests: [not_null, unique]
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('tpch','customer')
                field: c_custkey
      - name: customer_name
      - name: order_year

  - name: stg_customer
    description: "Silver: cleaned customer."
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: nation_key
        tests: [not_null]

  - name: stg_lineitem
    description: "Silver: cleaned lineitem (order line grain)."
    columns:
      - name: order_key
        tests: [not_null]
      - name: line_number
        tests: [not_null]

  # Gold
  - name: customer_revenue
    description: "Gold: total revenue per customer from LINEITEM * (1 - discount)."
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_name
      - name: total_revenue
        tests: [not_null]

  # Gold
  - name: dim_customer
    description: "Dimension: one row per customer with nation."
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_name
        tests: [not_null]
      - name: nation_name

  - name: fact_order_line
    description: "Fact: order line grain with line_revenue."
    columns:
      - name: order_key
        tests: [not_null]
      - name: line_number
        tests: [not_null]
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_key
      - name: line_revenue
        tests: [not_null]

  - name: customer_revenue_by_year
    description: "Aggregate: revenue by customer and year."
    columns:
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_key
      - name: order_year
        tests: [not_null]
      - name: total_revenue
        tests: [not_null]

  - name: nation_revenue
    description: "Aggregate: revenue by nation."
    columns:
      - name: nation_name
        tests: [not_null]
      - name: total_revenue
        tests: [not_null]

  - name: on_time_delivery_rate
    description: "KPI: on-time delivery rate (receiptdate <= commitdate) by nation and year."
    columns:
      - name: nation_name
        tests: [not_null]
      - name: order_year
        tests: [not_null]
